# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JKPopupExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'JKPopup', :path => '../'
  # Pods for JKPopupExample

  target 'JKPopupExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JKPopupExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
